// AUTO-GENERATED by model/demo/prepare_sih_demo.py - do not edit by hand.
// These are REAL measured metrics from the trained GeoSR-ESRGAN checkpoint,
// computed against a synthetic 2.5 m reference scene (see demo_metadata.json).
export interface SihDemoMetric {
  psnr: number | null;
  ssim: number | null;
  sam: number | null;
  ergas: number | null;
}
export interface SihDemoScene {
  id: string;
  category: string;
  title: string;
  location: string;
  gsd_input_meters: number;
  gsd_output_meters: number;
  scale_factor: number;
  bands: string[];
  band_descriptions: string[];
  crs: string;
  scene_note: string;
  reference_note: string;
  model: string;
  metrics: SihDemoMetric;
  independent_metric_check: SihDemoMetric & { psnr: number; ssim: number; sam: number; ergas: number };
  confidence_score: number | null;
  uncertainty_summary: Record<string, unknown>;
  inference_time_ms: number;
  reference_available: boolean;
  artifacts: Record<string, string | null>;
  web_previews: { lr_preview: string; sr_preview: string; confidence_preview: string };
}
export const SIH_DEMO_SCENES: SihDemoScene[] = [
  {
    "id": "urban",
    "category": "Urban",
    "title": "Urban Metropolitan District",
    "location": "Synthetic demonstration scene (not real satellite data)",
    "gsd_input_meters": 10.0,
    "gsd_output_meters": 2.5,
    "scale_factor": 4,
    "bands": [
      "B02",
      "B03",
      "B04",
      "B08"
    ],
    "band_descriptions": [
      "B02 (Blue, 10m)",
      "B03 (Green, 10m)",
      "B04 (Red, 10m)",
      "B08 (NIR, 10m)"
    ],
    "crs": "EPSG:32643 (WGS 84 / UTM Zone 43N)",
    "scene_note": "Synthetic Sentinel-2-like demonstration scene. Not real satellite imagery.",
    "reference_note": "Ground-truth reference computed from the degradation-free synthetic HR source (2.5 m) used only to score reconstruction; the 10 m input is the degraded product of that reference via model.datasets.degradation.",
    "model": "GeoSR-ESRGAN (trained, 2 epochs, geosr loss)",
    "metrics": {
      "psnr": 23.63628578186035,
      "ssim": 0.4303247928619385,
      "sam": 7.532297611236572,
      "ergas": 4.7568182945251465
    },
    "independent_metric_check": {
      "psnr": 23.636,
      "ssim": 0.4303,
      "sam": 7.532,
      "ergas": 4.757
    },
    "confidence_score": 9.138154029846191,
    "uncertainty_summary": {
      "confidence_score": 9.138154029846191,
      "confidence_mean": 0.09138154238462448,
      "confidence_std": 0.0009834090014919639,
      "max_uncertainty": 0.9119353294372559,
      "mean_uncertainty": 0.9086184501647949,
      "high_uncertainty_pixel_percent": 100.0
    },
    "inference_time_ms": 401.7,
    "reference_available": true,
    "artifacts": {
      "lr_input": "lr_input.tif",
      "sr_output": "sr_output.tif",
      "confidence_png": "confidence_preview.png",
      "confidence_tif": "confidence_sr_output.tif",
      "validation_report": "validation_report.json"
    },
    "web_previews": {
      "lr_preview": "/samples/sih/urban/lr_preview.png",
      "sr_preview": "/samples/sih/urban/sr_preview.png",
      "confidence_preview": "/samples/sih/urban/confidence_preview.png"
    }
  },
  {
    "id": "agriculture",
    "category": "Agriculture",
    "title": "Agricultural Cropping Zone",
    "location": "Synthetic demonstration scene (not real satellite data)",
    "gsd_input_meters": 10.0,
    "gsd_output_meters": 2.5,
    "scale_factor": 4,
    "bands": [
      "B02",
      "B03",
      "B04",
      "B08"
    ],
    "band_descriptions": [
      "B02 (Blue, 10m)",
      "B03 (Green, 10m)",
      "B04 (Red, 10m)",
      "B08 (NIR, 10m)"
    ],
    "crs": "EPSG:32643 (WGS 84 / UTM Zone 43N)",
    "scene_note": "Synthetic Sentinel-2-like demonstration scene. Not real satellite imagery.",
    "reference_note": "Ground-truth reference computed from the degradation-free synthetic HR source (2.5 m) used only to score reconstruction; the 10 m input is the degraded product of that reference via model.datasets.degradation.",
    "model": "GeoSR-ESRGAN (trained, 2 epochs, geosr loss)",
    "metrics": {
      "psnr": 25.197303771972656,
      "ssim": 0.5119014978408813,
      "sam": 7.605331897735596,
      "ergas": 5.255342960357666
    },
    "independent_metric_check": {
      "psnr": 25.197,
      "ssim": 0.5119,
      "sam": 7.605,
      "ergas": 5.255
    },
    "confidence_score": 7.822046279907227,
    "uncertainty_summary": {
      "confidence_score": 7.822046279907227,
      "confidence_mean": 0.07822046428918839,
      "confidence_std": 0.0005845166160725057,
      "max_uncertainty": 0.9238169193267822,
      "mean_uncertainty": 0.9217795133590698,
      "high_uncertainty_pixel_percent": 100.0
    },
    "inference_time_ms": 163.3,
    "reference_available": true,
    "artifacts": {
      "lr_input": "lr_input.tif",
      "sr_output": "sr_output.tif",
      "confidence_png": "confidence_preview.png",
      "confidence_tif": "confidence_sr_output.tif",
      "validation_report": "validation_report.json"
    },
    "web_previews": {
      "lr_preview": "/samples/sih/agriculture/lr_preview.png",
      "sr_preview": "/samples/sih/agriculture/sr_preview.png",
      "confidence_preview": "/samples/sih/agriculture/confidence_preview.png"
    }
  },
  {
    "id": "water",
    "category": "Water",
    "title": "Coastal / Inland Water Body",
    "location": "Synthetic demonstration scene (not real satellite data)",
    "gsd_input_meters": 10.0,
    "gsd_output_meters": 2.5,
    "scale_factor": 4,
    "bands": [
      "B02",
      "B03",
      "B04",
      "B08"
    ],
    "band_descriptions": [
      "B02 (Blue, 10m)",
      "B03 (Green, 10m)",
      "B04 (Red, 10m)",
      "B08 (NIR, 10m)"
    ],
    "crs": "EPSG:32643 (WGS 84 / UTM Zone 43N)",
    "scene_note": "Synthetic Sentinel-2-like demonstration scene. Not real satellite imagery.",
    "reference_note": "Ground-truth reference computed from the degradation-free synthetic HR source (2.5 m) used only to score reconstruction; the 10 m input is the degraded product of that reference via model.datasets.degradation.",
    "model": "GeoSR-ESRGAN (trained, 2 epochs, geosr loss)",
    "metrics": {
      "psnr": 28.15171241760254,
      "ssim": 0.7087187170982361,
      "sam": 15.292896270751953,
      "ergas": 7.5439348220825195
    },
    "independent_metric_check": {
      "psnr": 28.152,
      "ssim": 0.7087,
      "sam": 15.293,
      "ergas": 7.544
    },
    "confidence_score": 6.319403648376465,
    "uncertainty_summary": {
      "confidence_score": 6.319403648376465,
      "confidence_mean": 0.06319403648376465,
      "confidence_std": 0.0003283194964751601,
      "max_uncertainty": 0.9379706382751465,
      "mean_uncertainty": 0.9368059635162354,
      "high_uncertainty_pixel_percent": 100.0
    },
    "inference_time_ms": 195.9,
    "reference_available": true,
    "artifacts": {
      "lr_input": "lr_input.tif",
      "sr_output": "sr_output.tif",
      "confidence_png": "confidence_preview.png",
      "confidence_tif": "confidence_sr_output.tif",
      "validation_report": "validation_report.json"
    },
    "web_previews": {
      "lr_preview": "/samples/sih/water/lr_preview.png",
      "sr_preview": "/samples/sih/water/sr_preview.png",
      "confidence_preview": "/samples/sih/water/confidence_preview.png"
    }
  }
];
